### ISSUE TITLE
encodeURIComponent rather than encodeURI

### ISSUE THREAD

**Issue by sebastiankade** [Urigo/angular-embedly#32]
Hey @Urigo,

When constructing the embedly post you're using encodeURI() but really you should be using encodeURIComponent() as you are putting the encoded string as a query param.

This results in some urls failing to embed e.g. below: 
https://www.google.com/maps/@45.5067683,-122.6069459,11z

Cheers
Sebastian

**Comment by Urigo** [comment]
Hi @sebastiankade and thanks for the feedback.
Do you want to pull request the fix to get the credit you deserve?

**Comment by sebastiankade** [comment]
thanks @Urigo, but it's fine

If you could update the bower package too that would be great :)

**Comment by sebastiankade** [comment]
hey @Urigo did you manage to push this live yet?

**Comment by Tomtomgo** [comment]
Version 0.0.8 is available from Bower.
